Load maps based on URL
yapms/yapms pull request #109
Opened 2023-02-13 23:04 UTC by Flizzyclone

This PR changes the loading of maps to be based off of URL slugs. To do this, all file names for maps now should follow the following format:
[country]-[map]-[year].svg     *e.x: usa-presidential-2022.svg*

You can go to localhost:8081/app/predetermined/regions/example.svg to load the predetermined regions example and verify that this works.

Code Changes:
- Moves all maps from /src/lib/assets to /src/lib/assets/maps, done mainly to keep glob importing from importing any other SVGs we may put into /assets
- Adds a load function in +page.server.ts that sends params to +page.svelte as "data".
- Adds functionality into +page.svelte to check for a map corresponding to URL slug and loads that map if it is valid. If that map does not exist, it will automatically load usa-presidential-2022.
- Fixes an issue where any URL other than /usa/presidential/2022 would be redirected back to /usa/presidential/2022 if not loading JSON.

Closes #105

2023-02-21 04:09 UTC, Fish1 requested changes
Just need to convert it to run fully client side.

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/+page.server.ts
> +};
This shouldn't be used, I think the application should run on the client side as much as possible.

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/+page.svelte
> +	//{country:'usa',map:'presidential',year:'2022'}
We don't need to load the URL data from the server.

You can get the URL from the client like this.

import $page from "$app/stores";
const url = $page.url.pathname;

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/+page.svelte
> +	//The query section is there to make sure the SVG contents are imported raw, seeing as you cannot glob import with .svg?raw
I think comments can be a little more succinct, they should explain what is happening. You don't need to explain why you did what you did, unless it's super necessary.

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/+page.svelte
> +				{:then importedMap}<div use:setupMap class="overflow-hidden h-full">
div should be on a new line

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/+page.svelte
> +	if (imports[`/src/lib/assets/maps/${data.country}-${data.map}-${data.year}.svg`] !== undefined) { currentMap = `/src/lib/assets/maps/${data.country}-${data.map}-${data.year}.svg`; }
This is a bit long, can it be put on multiple lines?

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/+layout.svelte
>  		}
I think we need this so the /app url gets redirected to something if the m= is missing. But actual pages don't get redirected.
```ts
if (map === "") {

	if ($page.url.pathname === "/app") {
		await goto("/app/usa/presidential/2022");
	}

	return;
}
```

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/+layout.svelte
> +			await goto($page.url);
This can go back to redirecting to ```await goto("/app/usa/presidential/2022");``` because it should be the default if something goes wrong.

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/+page.server.ts
> +};
Just leave the ```export const prerender = true```

2023-02-21 04:09 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/+page.svelte
> +	console.log(imports)
Shouldn't have console logs.

2023-02-22 15:10 UTC, Flizzyclone commented
Changed to use page store and therefore run clientside... looks like we have some merge conflicts to be fixed when we merge in, so not much I can do for now.

2023-02-23 02:02 UTC, Fish1 approved these changes
LGTM. I just removed the package-lock.json

2023-02-23 02:05 UTC, merged