Input validation for edit region modal
yapms/yapms pull request #124
Opened 2023-03-03 02:48 UTC by Flizzyclone

This PR disables the confirm button in the edit region modal when an invalid input is given for the number of electors.

![image](https://user-images.githubusercontent.com/42476312/222618698-8d85d72f-c1d6-4b56-ace6-0e9cdb944154.png)
![image](https://user-images.githubusercontent.com/42476312/222618701-07da60e1-d7df-47a9-8db4-283ce3599ca0.png)

Summary of Code Changes:
- Adds a new property, confirmDisabled to EditRegionModalStore. This is set to false when the modal is closed, and is only set to true when an invalid input is entered.
- Adds required to the input element in order to not allow null values
- Adds an on:input function to control the value of confirmDisabled. The checkValidity() function will return false for anything that is not a non-negative integer.

Closes #101

2023-03-04 23:22 UTC, Fish1 commented on apps/yapms/src/routes/app/[country]/[map]/[year]/initialize/LoadRegions.ts
> +		confirmDisabled: false
I don't think this needs to be controlled globally from a store, it could be controled inside the modal itself.

2023-03-04 23:37 UTC, Fish1 requested changes
This shouldn't be a global store, all the information needed for the logic is contained within the modal.

2023-03-04 23:37 UTC, Fish1 commented on apps/yapms/src/lib/components/modals/editregionmodal/EditRegionModal.svelte
> +			<button class="btn btn-success" on:click={confirm} disabled={confirmDisabled}>
I think what you could do here is simply check if the newValue is out of bounds, set disabled to true.

2023-03-04 23:37 UTC, Fish1 commented on apps/yapms/src/lib/components/modals/editregionmodal/EditRegionModal.svelte
>  	$: newValue = value ?? 0;
Maybe have a dynamic "newValueOutOfBounds" variable here that does the logic for checking outOfBounds.

2023-03-04 23:37 UTC, Fish1 commented on apps/yapms/src/lib/components/modals/editregionmodal/EditRegionModal.svelte
>  	$: newValue = value ?? 0;
```js
$: newValueOutOfBounds = newValue < 0;
```

2023-03-11 04:50 UTC, Flizzyclone commented
Reworked the check to disable the "Confirm" button to be based on newValue. Could have this be a dynamic variable if you want, just lmk. @Fish1

2023-03-11 05:00 UTC, Fish1 approved these changes
LGTM

2023-03-11 05:00 UTC, merged