Beta Modal & Removal of Nonexistent Links
yapms/yapms pull request #173
Opened 2023-06-10 06:44 UTC by Flizzyclone

This PR adds a modal containing a notice that yapms2 is in beta to the home page. This modal will only show up in prod, so to see it you will need to run `npm run build` and then `npm run preview`. I do this by using `!dev` as a condition for the modal to show up.

![image](https://github.com/yapms/yapms/assets/42476312/19fd7c6c-3bdb-465e-9363-edff1d5ce816)

This PR also removes cards on the home page for nations other than the U.S, as those links would lead back to the USA 2024 map and were causing confusion.

Summary of Code Changes:
- Adds BetaModal & BetaModalStore
- Removes countries other than USA from MapSelection.json

Closes #172 and #170

2023-06-10 06:45 UTC, Flizzyclone commented
Ope sorry Fish, didn't see that you assigned yourself to this one. Feel free to rewrite as needed.

2023-06-10 12:22 UTC, Fish1 requested changes
It looks good!

If you could just use the ModalBase layout, that would be good. I've been using it for new modals, just haven't gone through and replaced them all. It just removes some boiler plate, and lets us tweak the layout of the modals without needing to change all the files.

The edittossupmodal uses it like this.
![image](https://github.com/yapms/yapms/assets/13600696/d25dea4a-ace6-4698-b632-19b0d5372ee4)

2023-06-10 12:33 UTC, Fish1 requested changes

2023-06-10 12:33 UTC, Fish1 commented on apps/yapms/src/lib/components/modals/betamodal/BetaModal.svelte
> +		</p>
This layout should be controlled by a flex box with a gap, like the above title is. But the flex box can flex vertically.

2023-06-10 15:24 UTC, Flizzyclone commented
I have addressed all issues. For the icon, I added an additional slot to ModalBase since you cannot pass HTML like you can with JSX in React. This doesn't throw off other modals using ModalBase, just allows us to add in icons.

2023-06-11 15:29 UTC, Fish1 approved these changes
Oh yeah, I like the slot idea, nice!

LGTM

2023-06-11 15:30 UTC, merged