MoreMapsModal Rework
yapms/yapms pull request #202
Opened 2023-06-28 00:32 UTC by Flizzyclone

This PR reworks MoreMapsModal by changing how it gets it's data from a json file to filtering Titles.json

Summary of Code Changes:
- Changes the route property on HomeLinkData to optional, adds optional routes prop
- Adds title prop to MoreMapsModalStore, changes key (string) prop to keys (string[])
- Changes the $maps variable in MoreMapsModal to being an array of Title objects matching paths defined in the routes property in MapSelection
- Adds routes for USA and U.S House

Closes #141

2023-07-01 16:00 UTC, Fish1 requested changes

2023-07-01 16:00 UTC, Fish1 commented on apps/yapms/src/lib/components/homepage/MapSelectionCard.svelte
> +		console.log(keys);
Remove console logs.

2023-07-01 16:00 UTC, Fish1 commented on apps/yapms/src/lib/types/HomeLinkData.ts
>  };
It's a bit confusing to have this data struct serve dual purposes. The routes and route parameters are doing two things, but they can both be entered, I'm not sure what it would mean if a HomeLinkData had a route and a routes.

There should be two data structures, one that models clicking a button to open a map. And another that is for opening a modal.

2023-07-01 16:00 UTC, Fish1 commented on apps/yapms/src/lib/components/modals/moremapsmodal/MoreMapsModal.svelte
>  	};
I don't think the second expression of the or statement ever executes here. An array will always be true.

2023-07-02 16:41 UTC, Flizzyclone commented
Alright I have broken these into two data structures, HomeLinkData and HomeModalData. They will now be defined separately in MapSelection.json under the "links" and "modal" properties respectively. Modal buttons will always render after other links. Please re-review.

2023-07-02 17:41 UTC, Fish1 approved these changes
LGTM. Just for future note, when making type definitions, you don't need to add the word "Data" to the end of them.

2023-07-02 17:41 UTC, merged