Home Page
yapms/yapms pull request #85
Opened 2022-12-29 17:34 UTC by Flizzyclone

Adds a proper design for the home page, looks like below:
Desktop (1920x1080):
![image](https://user-images.githubusercontent.com/42476312/209987942-4976105a-886e-4db7-a197-c1c91234b63e.png)

Mobile (Pixel 5):
![image](https://user-images.githubusercontent.com/42476312/209988003-199d771c-1a64-4eda-a722-80dd17e4d0fb.png)

Tablet (Ipad Air)
![image](https://user-images.githubusercontent.com/42476312/209988086-86f32613-cbfa-414c-8eb6-b23a9d6fdacd.png)

"More" buttons (defined by a "modal" boolean prop) lead to a modal where you can select all maps:
![image](https://user-images.githubusercontent.com/42476312/209988159-3d0069fa-e3c8-4887-a7c6-8b0d103e41c2.png)

Summary of Code Changes:
- Redid page.svelte for the home page completely.
- Added Login icon
- Added "MoreMapsModal" for seeing all maps for a country. The modal is constructed by reading data from MapList.json which contains information about maps organized by country "key". For usa, its 'usa'.
- Created HomePageSidebar, contains the social links & updates.
- Created MapSelectionCard, constructed by props passed to it, MapSelectionTitle (similar to ModalTitle), and mapSelectionGrid (simple div)
- Added countrybackgrounds in static so page.svelte can access them.

Login button and updating the "updates" section via API are not yet functional.
Closes #60

2022-12-29 17:51 UTC, Fish1 commented
Looking good! A couple things I just noticed skimming over it. But we can probably just offload these into different issues.

1) The social links have wrapping enabled, causing this.
![image](https://user-images.githubusercontent.com/13600696/209990258-6f537377-8590-49b3-af82-21d46a51e253.png)

2) I think the medium size, like on your iPad is a bit strange. The Update sidebar is larger than the main content of the page. Maybe we should make the update sidebar be horizontal on the bottom of the screen.
![image](https://user-images.githubusercontent.com/13600696/209990542-0ffdbc34-df63-469c-a156-4d67d34f507e.png)

I'll do a review of the code in a bit.

2022-12-29 17:54 UTC, Flizzyclone commented
> Looking good! A couple things I just noticed skimming over it. But we can probably just offload these into different issues.
> 
> 1. The social links have wrapping enabled, causing this.
>    ![image](https://user-images.githubusercontent.com/13600696/209990258-6f537377-8590-49b3-af82-21d46a51e253.png)
> 2. I think the medium size, like on your iPad is a bit strange. The Update sidebar is larger than the main content of the page. Maybe we should make the update sidebar be horizontal on the bottom of the screen.
>    ![image](https://user-images.githubusercontent.com/13600696/209990542-0ffdbc34-df63-469c-a156-4d67d34f507e.png)
> 
> I'll do a review of the code in a bit.

Good idea with having the updates be on the bottom, I was struggling with what to do with that size.

2022-12-29 18:29 UTC, Fish1 requested changes
Looks good! Just a few organizational and formatting things.

1) All folders should be all lower case, and all components should be Pascal Case.
![image](https://user-images.githubusercontent.com/13600696/209991644-839e76b1-144b-49d1-b3b8-c43cd4723411.png)

2) The images of the the country backgrounds should be in the src code assets, and imported directly into the code.

![image](https://user-images.githubusercontent.com/13600696/209994258-639cc60e-d6bc-402f-8619-e2d8f43456a4.png)

2022-12-29 18:29 UTC, Fish1 commented on apps/yapms/src/lib/assets/other/MapList.json
> +		"links": [
This file should be put into a more descriptive folder. Not just a folder called "other".

2022-12-29 18:29 UTC, Fish1 commented on apps/yapms/src/lib/assets/other/MapSelection.json
> +		"cards": [
This file should be put into a more descriptive folder. Not just a folder called "other".

2022-12-29 18:29 UTC, Fish1 commented on apps/yapms/src/lib/components/homePage/MapSelectionCard.svelte
> +        <div class="grid gap-4 {doubleCols ? "grid-cols-2": ""}">
Dynamic class should use sveltes dynamic class capabilities.

you can do ```class:grid-cols-2={doubleCols}```

2022-12-29 18:29 UTC, Fish1 commented on apps/yapms/src/routes/+page.svelte
> +</svelte:head>
The svelte:head tag should go directly below the <script> tag. Just for organization.

2022-12-29 18:29 UTC, Fish1 commented on apps/yapms/src/routes/+page.svelte
> +<div class="navbar bg-base-200 h-[10%]">
This ```h-[10%]``` can be removed. I think.

2022-12-29 18:29 UTC, Fish1 commented on apps/yapms/src/routes/+page.svelte
> +<div class="flex flex-row w-full h-[90%]">
This h-[90%] can be removed, also.

2022-12-29 18:40 UTC, Fish1 commented
Oh, sorry, I see why those height percentages were there.

But those should be reformatted into using flex boxes, similar to how it's managed on the app route. I don't think this is the exact solution, but something like it.
![image](https://user-images.githubusercontent.com/13600696/209995270-bfda3e42-96d5-4cf7-8924-485d2aacc511.png)

2022-12-29 22:16 UTC, Flizzyclone commented
I used percentages because flex has an odd issue. When scrolling to the bottom of the div with all the selection cards in it, the last one will be cut off.
![image](https://user-images.githubusercontent.com/42476312/210016088-20c03005-51a6-449c-919d-8ea38eb00d3d.png)

Using flex, I can fix this by having a fake, invisible card below
![image](https://user-images.githubusercontent.com/42476312/210016121-723844c7-d8b1-4371-a3fb-1cc0216c714a.png)
![image](https://user-images.githubusercontent.com/42476312/210016127-7e5a923f-b6c3-424d-8770-0fccab78e84a.png)

2022-12-29 22:31 UTC, Flizzyclone commented
Not sure why the lint failed on this... pnpm run format produces no issues and it looks like there might have been an issue copying files on Github's end.

2022-12-30 04:02 UTC, Flizzyclone commented
@Fish1, countrybackgrounds must be in static. Otherwise, components within the HTML cannot access it when building. Doesn't work like an SVG where we return the svg data itself from the component unfortunately.
`yapms:build: Error: Not found: /src/lib/assets/countrybackgrounds/usa.webp
yapms:build:     at resolve (file:///home/runner/work/yapms/yapms/apps/yapms/.svelte-kit/output/server/index.js:3017:18)
yapms:build:     at resolve (file:///home/runner/work/yapms/yapms/apps/yapms/.svelte-kit/output/server/index.js:2904:34)
yapms:build:     at options.hooks.handle (file:///home/runner/work/yapms/yapms/apps/yapms/.svelte-kit/output/server/index.js:3134:59)
yapms:build:     at respond (file:///home/runner/work/yapms/yapms/apps/yapms/.svelte-kit/output/server/index.js:2902:42)
yapms:build: file:///home/runner/work/yapms/yapms/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:36
yapms:build: 				throw new Error(format(details));
yapms:build: 				      ^
yapms:build: 
yapms:build: Error: 404 /src/lib/assets/countrybackgrounds/usa.webp (linked from /)
yapms:build:     at file:///home/runner/work/yapms/yapms/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:36:11
yapms:build:     at save (file:///home/runner/work/yapms/yapms/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:349:4)
yapms:build:     at visit (file:///home/runner/work/yapms/yapms/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:199:3)`

Error building when countrybackgrounds in src

2022-12-31 00:55 UTC, Fish1 commented
This is what I tried on the home page, it should let you remove that blank card at the bottom.

```
<div class="flex flex-col h-full overflow-hidden">

	<div class="navbar bg-base-200">
		<div class="navbar-start"></div>
		<div class="navbar-center">
			<h1 class="text-2xl font-bold m-auto hidden lg:inline">Yet Another Political Map Simulator</h1>
			<h1 class="text-2xl font-bold m-auto inline lg:hidden">YAPms</h1>
		</div>
		<div class="navbar-end">
			<button class="btn px-8 btn-primary mr-2 hidden md:inline">Login</button>
			<button class="btn btn-square mr-2 inline md:hidden"><Login class="h-8 m-auto"/></button>
		</div>
	</div>

	<div class="flex flex-row h-full overflow-hidden">
		<HomePageSidebar/>
		<div class="divider md:divider-horizontal ml-0 w-0" />
		<div class="flex-1 md:pr-5 overflow-scroll">
			{#each mapSelectSections as section}
				<MapSelectionTitle title={section.title}></MapSelectionTitle>
				<MapSelectionGrid>
					{#each section.cards as card}
						<MapSelectionCard name={card.name} background={card.bg} alt={card.alt} doubleCols={card.doubleCols} links={card.links}></MapSelectionCard>
					{/each}
				</MapSelectionGrid>
			{/each}
		</div>
	</div>
	
</div>```

2022-12-31 01:02 UTC, Fish1 commented
Running the image imports through rollup imports would be ideal though, as it provides cache breaking features, and you can run them through optimizes.

But hard coding the URL should be fine for now.

2022-12-31 01:02 UTC, Fish1 requested changes
See above two posts.

2023-01-02 04:28 UTC, Flizzyclone commented
Unsure of what magic you did with the first post but it seems to have worked, and I have implemented it.

2023-01-03 02:44 UTC, Fish1 approved these changes
LGTM

2023-01-03 02:44 UTC, merged